development:
  adapter: postgresql
  username: anton
  password: 123 
  port: 5432
  host: 127.0.0.1
  database: ae_dev

test:
  adapter: postgresql
  username: anton
  password: 123 
  port: 5432
  host: 127.0.0.1
  database: ae_test
  min_messages: WARNING
